### PR TITLE
apply custom filters to chart-verifier install requests

### LINKED ISSUE #108: [BUG] openshift-tools-installer fails to find chart-verifier releases
### Version

All versions

### Describe the bug

openshift-tools-installer fails to find chart-verifier 1.13.6 release binary tarballs in the list of release assets. 

### Steps to reproduce, workflow links, screenshots

- No steps to reproduce because we've worked around this issue for the [Chart Verifier 1.13.6](https://github.com/redhat-certification/chart-verifier/releases/tag/1.13.6) release to unblock users.

- See https://github.com/redhat-certification/chart-verifier/issues/463 for a detailed synopsis of what was going wrong.

### Context

I maintain https://github.com/redhat-certification/chart-verifier.

The problem here is the filtering that's applied within openshift-tools-installer. Chart Verifier undergoes the default release asset filtering (`filterByOs`, `filterByArch`, `filterByZipped`).

In the past, we only had a single release asset that was published. When openshift-tools-installer encounters only a single release asset, it skips remaining filtering (i.e. all filters). Now that we have 2 assets, the first filter (`filterByOs`) is filtering out everything, and returning 0 assets.

Chart Verifier either needs to rename their release asset, or needs custom filters here. I'm leaning the filtering route for now because there may be other locations that use our release asset names as they exist. 

I've got some filters that work. I'll submit them as a PR here shortly.

### PR DESCRIPTION
**Pull request by komish**
### Description

Applies custom filters to the chart-verifier (via github) installation.

### Related Issue(s)

fixes #108 

### Checklist

- [ ] This PR includes a documentation change
- [x] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [x] This change is not user-facing
- [x] This change is a patch change
- [ ] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

- Set custom file-finding filters for chart-verifier installs to fix a bug in detecting the release asset when multiple assets are present.

### CODE REVIEW

**Comment by komish** [comment]
PTAL @divyansh42

**Comment by divyansh42** [comment]
@komish Thanks for the PR
CI tests were disabled due to no activity. I have enabled them again.
Could you please do a force push (or empty push) to trigger the tests again.

**Comment by komish** [comment]
@divyansh42 sure thing, coming momentarily

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
Changes should reflect in `v1`. `v1.13` and `v1.13.1` tags

**Pull request merged**
